import test from 'node:test';import assert from 'node:assert/strict';import {validate} from '../src/config.js';import {redact,assertCommand} from '../src/safety.js';import {classify,acquireLock,atomicWrite,readJson} from '../src/state.js';import {plan} from '../src/schedule.js';import {loopback} from '../src/probes.js';import {command} from '../src/process.js';import {join} from 'node:path';import {tmpdir} from 'node:os';import {rm} from 'node:fs/promises';
test('classification lifecycle',()=>{assert.equal(classify({status:'fail',signature:'x'},{}).classification,'new');assert.equal(classify({status:'fail',signature:'x'},{status:'fail',signature:'x'}).classification,'repeated');assert.equal(classify({status:'pass'},{status:'fail'}).classification,'recovered');assert.equal(classify({status:'pass'},{classification:'recovered'}).classification,'retirement candidate');assert.equal(classify({status:'pass'},{status:'pass'}).classification,'unchanged')});
test('redaction and allowlist',()=>{assert.match(redact('Bearer abcdef token=abc'),/REDACTED/);assert.throws(()=>assertCommand('git',['push']));assert.throws(()=>assertCommand('gh',['api','user']));assert.equal(assertCommand('git',['ls-remote','origin']),true)});
test('configuration rejects unsafe content',()=>{assert.throws(()=>validate({publicEndpoints:['http://example.invalid']}));assert.throws(()=>validate({password:'value'}));assert.throws(()=>validate({github:{strategy:'bogus'}}));assert.equal(validate({}).schedule.time,'09:00')});
test('all scheduler plans use absolute executable and CLI paths',()=>{for(const x of ['win32','darwin','linux','cron']){const p=plan(x,validate({}),process.execPath);assert.match(p.command,/canary/);assert.equal(p.node,process.execPath);assert.match(p.cli,/cli\.js$/)}});
test('lock prevents overlap and releases',async()=>{const release=await acquireLock();await assert.rejects(()=>acquireLock());await release();const again=await acquireLock();await again()});
test('atomic JSON write',async()=>{const p=join(tmpdir(),'canary-test-'+process.pid+'.json');try{await atomicWrite(p,{a:1});assert.deepEqual(await readJson(p,{}),{a:1})}finally{await rm(p,{force:true})}});
test('loopback closes listener',async()=>{const c=new AbortController();assert.equal((await loopback(c.signal,3000)).status,'pass')});
test('optional executable absence is reported',async()=>{const r=await command('netlify',['--version'],{timeout:1000});assert.ok(['ok','ENOENT','exit'].includes(r.reason))});
