#!/usr/bin/env node
import {load,root} from './config.js';import {runProbes} from './probes.js';import {acquireLock,persist} from './state.js';import {latest,markdown} from './report.js';import {plan,choose,status,install,remove} from './schedule.js';import {command} from './process.js';import {redact} from './safety.js';
const say=x=>console.log(typeof x==='string'?redact(x):JSON.stringify(redact(x),null,2));
const args=process.argv.slice(2),op=args[0]||'help';
const controller=new AbortController();for(const s of ['SIGINT','SIGTERM'])process.on(s,()=>controller.abort());
async function main(){const c=await load();if(op==='canary'){const dry=args.includes('--dry');if(dry){say({dry:true,probes:['runtime','git.remote','git.read','github.api','github.auth.advisory','http.loopback','http.public','netlify.status'],config:redact({...c,publicEndpoints:c.publicEndpoints.map(()=>'<configured HTTPS endpoint>')})});return}const unlock=await acquireLock();try{const run={started:new Date().toISOString(),results:await runProbes(c,controller.signal)};run.ended=new Date().toISOString();const file=await persist(run,c.retention);say(markdown(run));say(`Report: local/reports/${file}`);if(run.results.some(r=>r.status==='fail'))process.exitCode=1}finally{await unlock()}return}
if(op==='report'){const x=await latest();say(x?markdown(x):'No report yet');return}
if(op==='auth:doctor'){const g=c.github.strategy,n=c.netlify.strategy;const checks={strategy:{github:g,netlify:n},context:process.env.CI?'CI':process.env.SESSIONNAME?'interactive or scheduled Windows':'terminal or scheduler',sshAgentProvider:!!(process.env.SSH_AUTH_SOCK||process.env.SSH_AGENT_PID),gitCredentialManagerConfigured:false,githubProviderAppearsAvailable:false,githubAuthenticatedReadSucceeded:false,netlifyCliAvailable:false,netlifyCliAuthenticated:false,remediation:[]};const helper=await command('git',['config','--get','credential.helper'],{timeout:c.timeoutMs});checks.gitCredentialManagerConfigured=helper.code===0&&/manager/i.test(helper.stdout);checks.githubProviderAppearsAvailable=g==='environment'?!!process.env[c.github.environmentVariable]:g==='ssh'?checks.sshAgentProvider:g==='https'?checks.gitCredentialManagerConfigured:g==='auto';if(c.github.owner&&c.github.repository&&g!=='disabled'){const r=await command('gh',['api',`repos/${c.github.owner}/${c.github.repository}`],{timeout:c.timeoutMs});checks.githubAuthenticatedReadSucceeded=r.code===0}else checks.remediation.push('Configure a GitHub repository and strategy for authenticated diagnosis.');const v=await command('netlify',['--version'],{timeout:c.timeoutMs});checks.netlifyCliAvailable=v.code===0;if(v.code===0&&n!=='disabled'){const r=await command('netlify',['status'],{timeout:c.timeoutMs});checks.netlifyCliAuthenticated=r.code===0}if(!checks.githubAuthenticatedReadSucceeded)checks.remediation.push('Check the selected provider in the current user context; scheduler environment may lack agent sockets or environment variables.');say(checks);return}
if(op.startsWith('schedule:')){const platform=args.find(x=>x.startsWith('--platform='))?.split('=')[1]||await choose();const p=plan(platform,c);if(op==='schedule:plan'){say(p);return}if(platform!==process.platform&&!(process.platform==='linux'&&platform==='cron'))throw Error('Schedule mutation requires native platform');if(op==='schedule:status'){const r=await status(p);const prior=p.scheduler==='Windows Task Scheduler'?r.stdout.match(/^Last Result:\s*(.*)$/mi)?.[1]||'unavailable':r.code===0?'available':'unavailable';say({...p,installed:r.code===0,priorResult:prior});return}if(!args.includes('--confirm'))throw Error('Schedule mutation requires --confirm');const r=op==='schedule:install'?await install(p):op==='schedule:remove'?await remove(p):null;if(!r)throw Error('Unknown schedule command');say({scheduler:p.scheduler,identity:p.identity,code:r.code,summary:r.code===0?'Done':'Scheduler command failed'});if(r.code!==0)process.exitCode=1;return}
say('Commands: canary [--dry], report, auth:doctor, schedule:plan [--platform=win32|darwin|linux|cron], schedule:install --confirm, schedule:status, schedule:remove --confirm')}
main().catch(e=>{console.error(redact(e.message||String(e)));process.exitCode=1});
