import {createServer} from 'node:http';import {command} from './process.js';import {redact} from './safety.js';
const fixture='<!doctype html><title>Canary fixture</title><h1>canary-ok</h1>';
export async function loopback(signal,timeout){let server;try{server=createServer((req,res)=>{res.setHeader('content-type','text/html');res.end(fixture)});await new Promise((ok,no)=>{server.once('error',no);server.listen(0,'127.0.0.1',ok)});const port=server.address().port;const r=await fetch(`http://127.0.0.1:${port}/`,{signal:AbortSignal.any([signal,AbortSignal.timeout(timeout)])});return r.ok&&(await r.text())===fixture?{status:'pass',evidence:'Loopback fixture matched'}:{status:'fail',evidence:'Loopback fixture mismatch'}}finally{if(server)await new Promise(resolve=>server.close(resolve))}}
export async function runProbes(c,signal){const tasks=[];const add=(id,layer,operation,fn)=>{if(c.probes[id]===false)return;tasks.push({id,layer,operation,fn})};
if(c.commands){for(const name of ['node','npm','git','gh','netlify'])add(`runtime.${name}`,'runtime',`${name} --version`,async()=>{const r=await command(name,['--version'],{timeout:c.timeoutMs,signal});return {status:r.code===0?'pass':name==='netlify'?'skipped':'fail',evidence:r.code===0?`${name} available`:`${name} unavailable`,signature:r.reason}})}
add('git.remote','git','git remote get-url origin',async()=>{const r=await command('git',['remote','get-url','origin'],{timeout:c.timeoutMs,signal});if(r.code!==0)return {status:'inconclusive',evidence:'No origin remote configured'};const remote=r.stdout.trim();const ok=/^(https:\/\/github\.com\/|git@github\.com:)/.test(remote)&&(!c.expectedRemote||remote===c.expectedRemote);return {status:ok?'pass':'fail',evidence:ok?'GitHub remote protocol and hostname matched':'Remote did not match expected GitHub identity',signature:'remote-mismatch'}});
add('git.read','git','git ls-remote origin',async()=>{const r=await command('git',['ls-remote','origin'],{timeout:c.timeoutMs,signal});return {status:r.code===0?'pass':'fail',evidence:r.code===0?'Read-only Git remote access succeeded':'Read-only Git remote access failed',signature:r.reason}});
if(c.github.owner&&c.github.repository)add('github.api','github',`gh api repos/<configured owner>/<configured repository>`,async()=>{const r=await command('gh',['api',`repos/${c.github.owner}/${c.github.repository}`],{timeout:c.timeoutMs,signal});return {status:r.code===0?'pass':'fail',evidence:r.code===0?'GitHub read-only API succeeded':'GitHub read-only API failed',signature:r.reason}});
add('github.auth.advisory','github','gh auth status',async()=>{const r=await command('gh',['auth','status'],{timeout:c.timeoutMs,signal});return {status:r.code===0?'pass':'inconclusive',evidence:r.code===0?'GitHub CLI auth status succeeded':'Auth status advisory unavailable; practical access must be judged separately'}});
if(c.loopback)add('http.loopback','http','GET loopback fixture',()=>loopback(signal,c.timeoutMs));
for(const [i,url] of c.publicEndpoints.entries())add(`http.public.${i}`,'http','GET configured HTTPS endpoint',async()=>{const r=await fetch(url,{method:'GET',redirect:'follow',signal:AbortSignal.any([signal,AbortSignal.timeout(c.timeoutMs)])});return {status:r.ok?'pass':'fail',evidence:`HTTPS status ${r.status}`,signature:`http-${r.status}`}});
if(c.netlify.strategy!=='disabled')add('netlify.status','netlify','netlify status',async()=>{const v=await command('netlify',['--version'],{timeout:c.timeoutMs,signal});if(v.code!==0)return {status:'skipped',evidence:'Optional Netlify CLI absent'};const r=await command('netlify',['status'],{timeout:c.timeoutMs,signal});return {status:r.code===0?'pass':'inconclusive',evidence:r.code===0?'Netlify CLI status succeeded':'Netlify CLI status unavailable',signature:r.reason}});
const results=[];for(const t of tasks){const start=new Date();let x;try{x=await t.fn()}catch(e){x={status:signal.aborted?'inconclusive':'fail',evidence:signal.aborted?'Interrupted':redact(String(e.message||e)),signature:redact(e.name||'error')}}const end=new Date();results.push(redact({id:t.id,layer:t.layer,status:x.status,started:start.toISOString(),ended:end.toISOString(),durationMs:end-start,operation:t.operation,evidence:x.evidence,signature:x.signature||'',classification:'unchanged'}));if(signal.aborted)break}return results}
