import {join} from 'node:path';import {homedir} from 'node:os';import {mkdir,writeFile,readFile} from 'node:fs/promises';import {spawn} from 'node:child_process';import {root,local} from './config.js';import {logDir} from './state.js';
const task='Agent Toolchain Canary',label='dev.toolchain.canary';
const xmlEscape=s=>String(s).replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]));
const q=s=>`"${s.replace(/"/g,'\\"')}"`;
const weekdays=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
function next(day,time){const now=new Date(),d=new Date(now);const [h,m]=time.split(':').map(Number);d.setHours(h,m,0,0);d.setDate(d.getDate()+(weekdays.indexOf(day)-d.getDay()+7)%7);if(d<=now)d.setDate(d.getDate()+7);return d}
export function plan(platform,c,node=process.execPath){const cli=join(root,'src','cli.js'),args=[cli,'canary'],run=`${q(node)} ${q(cli)} canary`,when=next(c.schedule.day,c.schedule.time);if(platform==='win32')return {scheduler:'Windows Task Scheduler',identity:task,command:run,nextRun:when.toString(),node,cli,day:c.schedule.day,time:c.schedule.time};if(platform==='darwin')return {scheduler:'user launchd',identity:label,command:run,nextRun:when.toString(),node,cli,day:c.schedule.day,time:c.schedule.time};if(platform==='linux')return {scheduler:'user systemd timer',identity:'agent-toolchain-canary.timer',command:run,nextRun:when.toString(),node,cli,day:c.schedule.day,time:c.schedule.time};if(platform==='cron')return {scheduler:'user crontab',identity:'# agent-toolchain-canary',command:run,nextRun:when.toString(),node,cli,day:c.schedule.day,time:c.schedule.time};throw Error('Unsupported platform')}
async function exec(name,args,input){return new Promise(resolve=>{let out='',err='';const child=spawn(name,args,{shell:false,windowsHide:true,stdio:['pipe','pipe','pipe']});child.on('error',e=>resolve({code:null,stdout:'',stderr:e.code||'spawn error'}));child.stdout.on('data',d=>out+=d);child.stderr.on('data',d=>err+=d);child.on('close',code=>resolve({code,stdout:out,stderr:err}));child.stdin.end(input||'')})}
function windowsXml(p){const start=next(p.day,p.time);const boundary=`${start.getFullYear()}-${String(start.getMonth()+1).padStart(2,'0')}-${String(start.getDate()).padStart(2,'0')}T${p.time}:00`;const day=p.day;return `<?xml version="1.0" encoding="UTF-16"?><Task version="1.4" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task"><RegistrationInfo><Description>Agent Toolchain Canary</Description></RegistrationInfo><Triggers><CalendarTrigger><StartBoundary>${boundary}</StartBoundary><Enabled>true</Enabled><ScheduleByWeek><DaysOfWeek><${day}/></DaysOfWeek><WeeksInterval>1</WeeksInterval></ScheduleByWeek></CalendarTrigger></Triggers><Principals><Principal id="Author"><UserId>${xmlEscape(process.env.USERDOMAIN||'')}\\${xmlEscape(process.env.USERNAME||'')}</UserId><LogonType>InteractiveToken</LogonType><RunLevel>LeastPrivilege</RunLevel></Principal></Principals><Settings><MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy><DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries><StopIfGoingOnBatteries>false</StopIfGoingOnBatteries><AllowHardTerminate>true</AllowHardTerminate><StartWhenAvailable>true</StartWhenAvailable><Enabled>true</Enabled><ExecutionTimeLimit>PT30M</ExecutionTimeLimit></Settings><Actions Context="Author"><Exec><Command>${xmlEscape(p.node)}</Command><Arguments>${xmlEscape(q(p.cli)+' canary')}</Arguments><WorkingDirectory>${xmlEscape(root)}</WorkingDirectory></Exec></Actions></Task>`}
function launchdPlist(p){const d=weekdays.indexOf(p.day),[h,m]=p.time.split(':');return `<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0"><dict><key>Label</key><string>${label}</string><key>ProgramArguments</key><array><string>${xmlEscape(p.node)}</string><string>${xmlEscape(p.cli)}</string><string>canary</string></array><key>StartCalendarInterval</key><dict><key>Weekday</key><integer>${d===0?0:d}</integer><key>Hour</key><integer>${Number(h)}</integer><key>Minute</key><integer>${Number(m)}</integer></dict><key>StandardOutPath</key><string>${xmlEscape(join(logDir,'launchd.out.log'))}</string><key>StandardErrorPath</key><string>${xmlEscape(join(logDir,'launchd.err.log'))}</string></dict></plist>`}
function service(p){return `[Unit]\nDescription=Agent Toolchain Canary\n[Service]\nType=oneshot\nExecStart=${q(p.node)} ${q(p.cli)} canary\nWorkingDirectory=${q(root)}\n`}
function timer(p){return `[Unit]\nDescription=Agent Toolchain Canary weekly timer\n[Timer]\nOnCalendar=${p.day} *-*-* ${p.time}:00\nPersistent=true\nUnit=agent-toolchain-canary.service\n[Install]\nWantedBy=timers.target\n`}
function cronLine(p){const [h,m]=p.time.split(':');return `${Number(m)} ${Number(h)} * * ${weekdays.indexOf(p.day)} ${q(p.node)} ${q(p.cli)} canary >> ${q(join(logDir,'cron.log'))} 2>&1 # agent-toolchain-canary`}
export async function choose(platform=process.platform){if(platform!=='linux')return platform;const r=await exec('systemctl',['--user','show-environment']);return r.code===0?'linux':'cron'}
export async function status(p){if(p.scheduler==='Windows Task Scheduler')return exec('schtasks',['/Query','/TN',task,'/FO','LIST','/V']);if(p.scheduler==='user launchd')return exec('launchctl',['list',label]);if(p.scheduler==='user systemd timer')return exec('systemctl',['--user','status','agent-toolchain-canary.timer']);const r=await exec('crontab',['-l']);return {...r,stdout:r.stdout.split('\n').filter(x=>x.includes('# agent-toolchain-canary')).join('\n')}}
export async function install(p){const old=await status(p);if(old.code===0&&old.stdout.trim())return {code:0,stdout:'Already installed'};await mkdir(logDir,{recursive:true});if(p.scheduler==='Windows Task Scheduler'){const path=join(local,'state','task.xml');await mkdir(join(local,'state'),{recursive:true});await writeFile(path,'\uFEFF'+windowsXml(p),{encoding:'utf16le'});return exec('schtasks',['/Create','/TN',task,'/XML',path])}if(p.scheduler==='user launchd'){const path=join(homedir(),'Library','LaunchAgents',label+'.plist');await mkdir(join(homedir(),'Library','LaunchAgents'),{recursive:true});await writeFile(path,launchdPlist(p),{flag:'wx'});return exec('launchctl',['load',path])}if(p.scheduler==='user systemd timer'){const dir=join(homedir(),'.config','systemd','user');await mkdir(dir,{recursive:true});await writeFile(join(dir,'agent-toolchain-canary.service'),service(p),{flag:'wx'});await writeFile(join(dir,'agent-toolchain-canary.timer'),timer(p),{flag:'wx'});await exec('systemctl',['--user','daemon-reload']);return exec('systemctl',['--user','enable','--now','agent-toolchain-canary.timer'])}const oldCron=await exec('crontab',['-l']);return exec('crontab',['-'],(oldCron.code===0?oldCron.stdout.trimEnd()+'\n':'')+cronLine(p)+'\n')}
export async function remove(p){if(p.scheduler==='Windows Task Scheduler')return exec('schtasks',['/Delete','/TN',task,'/F']);if(p.scheduler==='user launchd'){const path=join(homedir(),'Library','LaunchAgents',label+'.plist');await exec('launchctl',['unload',path]);return (await import('node:fs/promises')).unlink(path).then(()=>({code:0,stdout:'Removed'}))}if(p.scheduler==='user systemd timer'){await exec('systemctl',['--user','disable','--now','agent-toolchain-canary.timer']);const fs=await import('node:fs/promises');const dir=join(homedir(),'.config','systemd','user');await fs.unlink(join(dir,'agent-toolchain-canary.timer'));await fs.unlink(join(dir,'agent-toolchain-canary.service'));return exec('systemctl',['--user','daemon-reload'])}const old=await exec('crontab',['-l']);return exec('crontab',['-'],old.stdout.split('\n').filter(x=>!x.includes('# agent-toolchain-canary')).join('\n'))}
